#!/usr/bin/env node
//
//  index.js
//  MerlinProjectMCPB
//
//  Node.js port of MerlinMCPShim/main.swift — keep the two in sync.
//
//  MerlinProjectMCPB is a lightweight command-line tool that lets MCP-capable agents
//  (Claude, Cursor, …) talk to the sandboxed MerlinProject app. It exists alongside the Swift
//  shim because Claude's Desktop Extension marketplace only accepts Node.js-based MCPB
//  extensions; the behavior of the two shims is identical.
//
//  Architecture:
//
//      IDE  ⇄  stdio  ⇄  shim Server (this process)  ⇄  shim Client (lazy)  ⇄  UDS  ⇄  live Server
//
//  The shim runs an MCP `Server` on stdio for the entire session and forwards `tools/call` /
//  `resources/read` to the live in-app server through a cached `Client` connected to the UDS
//  (Unix Domain Socket) in the shared App Group container. `tools/list` and `resources/list`
//  are answered locally from the bundled catalog snapshot, so the IDE always sees the same
//  metadata regardless of whether MerlinProject was running when the session started.
//
//  Host-app availability is detected by attempting the UDS connect: success implies the host app
//  is up *and* its `MCPSocketServer` has bound the socket; typical failure modes (`ENOENT` for a
//  missing socket file, `ECONNREFUSED` for a stale one left after a crash) mean the host app
//  isn't reachable yet. We deliberately do not auto-launch the host app — an MCP-aware IDE often
//  spawns the shim eagerly when the user opens it, and silently launching MerlinProject on every
//  such spawn would surprise users. Instead the shim returns a structured "Merlin Project is not
//  running" CallTool error and retries the UDS connect on every call, so the moment the user
//  launches MerlinProject the shim picks up on the next call without any MCP-client restart.

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
    CallToolRequestSchema,
    ListResourcesRequestSchema,
    ListToolsRequestSchema,
    ReadResourceRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

import { ShimBridge } from "./bridge.js";

// A closed stdout (IDE quit while we're flushing a reply) surfaces as an EPIPE error event in
// Node rather than a SIGPIPE signal; without a handler it would crash the shim. Exiting quietly
// is the right disposition here — there is nobody left to talk to.
process.stdout.on("error", (error) => {
    if (error?.code === "EPIPE") {
        process.exit(0);
    }
    throw error;
});

/// App Group shared by the sandboxed host application and the shims. The Swift side resolves the
/// container via `containerURL(forSecurityApplicationGroupIdentifier:)`, which on macOS maps to
/// `~/Library/Group Containers/<group-id>/`; this unsandboxed shim constructs the same path
/// directly.
const appGroupID = "9R6P9VZV27.net.projectwizards.merlinproject.mcp";

/// Name of the socket file inside the App Group container.
const socketFileName = "mcp.sock";

function die(message) {
    process.stderr.write(`MerlinMCPShim: ${message}\n`);
    process.exit(1);
}

/// Resolves the socket path inside the App Group container shared with the sandboxed host app.
/// `MERLIN_MCP_SOCKET` overrides it for development and testing.
function resolveSocketPath() {
    const override = process.env.MERLIN_MCP_SOCKET;
    if (override) {
        return override;
    }
    return path.join(os.homedir(), "Library", "Group Containers", appGroupID, socketFileName);
}

/// Loads the catalog snapshot generated by scripts/generate-catalog.js from the live server's
/// `tools/list` / `resources/list` (which in turn serve Swift's `MCPCatalog`), so the metadata
/// the shim answers locally is identical to what the in-app server serves.
function loadCatalog() {
    const catalogPath = path.join(path.dirname(fileURLToPath(import.meta.url)), "catalog.json");
    try {
        return JSON.parse(fs.readFileSync(catalogPath, "utf8"));
    } catch (error) {
        die(`Cannot load catalog.json: ${error.message}\nRun scripts/generate-catalog.js.`);
    }
}

// MARK: - Main

const socketPath = resolveSocketPath();
const catalog = loadCatalog();

const bridge = new ShimBridge(socketPath);

// Probe the live server once at startup so the IDE's `initialize` reply carries the live
// server's real `serverInfo.name` / `serverInfo.version` whenever MerlinProject happens to be
// running already. If the probe fails we fall back to a stub identity (`MerlinProject /
// 0.0.0-stub`) and the bridge will pick up the live server on the first CallTool / ReadResource
// after MerlinProject launches — without any MCP-client restart.
const liveInfo = await bridge.probeLiveServer();
const advertisedName = liveInfo?.name ?? catalog.serverName;
const advertisedVersion = liveInfo?.version ?? "0.0.0-stub";

if (liveInfo === null) {
    process.stderr.write(
        "MerlinMCPShim: MerlinProject is not reachable at startup; advertising stub identity.\n"
    );
}

const server = new Server(
    { name: advertisedName, version: advertisedVersion },
    {
        capabilities: {
            resources: { subscribe: false, listChanged: false },
            tools: { listChanged: false },
        },
    }
);

// `tools/list` and `resources/list` are served straight out of the bundled catalog snapshot —
// both this shim and the in-app server derive their tool/resource lists from Swift's
// `MCPCatalog` (the snapshot is generated from the live server's responses), so the metadata is
// identical by construction and we never have to round-trip through the live server just to
// answer a list request.
server.setRequestHandler(ListToolsRequestSchema, () => ({ tools: catalog.tools }));

server.setRequestHandler(ListResourcesRequestSchema, () => ({ resources: catalog.resources }));

// `tools/call` and `resources/read` need real document state, so they're forwarded through the
// bridge's cached `Client`. When the live server isn't reachable, `forwardCallTool` returns a
// CallTool result with `isError: true` and the user-facing "Merlin not running" message;
// `forwardReadResource` throws an McpError that the SDK Server wraps as a JSON-RPC error.
server.setRequestHandler(CallToolRequestSchema, (request) =>
    bridge.forwardCallTool(request.params)
);

server.setRequestHandler(ReadResourceRequestSchema, (request) =>
    bridge.forwardReadResource(request.params)
);

// Capture the IDE's `clientInfo` from its `initialize` request and forward it to the bridge,
// so the bridge's UDS Client uses the agent's real name (Cursor, Claude, …) when it
// handshakes against the live host-app server. Without this, the host's `MCPSession`
// records `"MerlinMCPShim"` for every connection and the toolbar popover's connected-tools
// list shows the shim instead of the agent.
server.oninitialized = () => {
    bridge.recordForwardedClientInfo(server.getClientVersion());
};

// When the IDE closes our stdin the transport shuts down; exit explicitly because a cached UDS
// connection to the live server would otherwise keep the event loop (and this process) alive.
server.onclose = () => {
    process.exit(0);
};

try {
    await server.connect(new StdioServerTransport());
} catch (error) {
    die(`Server failed to start: ${error}`);
}
